// <auto-generated />
using System;
using Dartware.Radiocamp.Clients.Windows.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dartware.Radiocamp.Clients.Windows.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201028071824_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Dartware.Radiocamp.Clients.Windows.Core.Models.WindowsRadiostation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StreamURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Radiostations");
                });

            modelBuilder.Entity("Dartware.Radiocamp.Clients.Windows.Hotkeys.Hotkey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Command")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModifierKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hotkeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f83fffd9-a1f8-499e-9a66-1f2d80bcb4cb"),
                            Command = 1,
                            IsEnabled = false,
                            Key = 0,
                            ModifierKey = 0
                        },
                        new
                        {
                            Id = new Guid("d884a1dc-fa68-4cdc-848d-d641c99554f5"),
                            Command = 2,
                            IsEnabled = false,
                            Key = 0,
                            ModifierKey = 0
                        },
                        new
                        {
                            Id = new Guid("c3ebb27f-098f-4908-841a-3d5de2d7b124"),
                            Command = 3,
                            IsEnabled = false,
                            Key = 0,
                            ModifierKey = 0
                        },
                        new
                        {
                            Id = new Guid("6bc66ad2-793f-4d15-892f-af385f09a3fa"),
                            Command = 4,
                            IsEnabled = false,
                            Key = 0,
                            ModifierKey = 0
                        },
                        new
                        {
                            Id = new Guid("49888dfa-c7be-46b6-8df4-d712f6ac7736"),
                            Command = 5,
                            IsEnabled = false,
                            Key = 0,
                            ModifierKey = 0
                        },
                        new
                        {
                            Id = new Guid("af12d4ac-cb18-4a08-8844-69c001daa30e"),
                            Command = 6,
                            IsEnabled = false,
                            Key = 0,
                            ModifierKey = 0
                        });
                });

            modelBuilder.Entity("Dartware.Radiocamp.Clients.Windows.Settings.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlwaysShowTrayIcon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExportRadiostationsAll")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExportRadiostationsCustomOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExportRadiostationsFavoritesOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExportRadiostationsFormat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExportRadiostationsOnlyFavoritesOrCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExportRadiostationsPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExportRadiostationsSaveFavoritesTags")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExportRadiostationsSaveSoundSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideApplicationOnCloseButtonClick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideApplicationOnMinimizeButtonClick")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideInTaskbar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideInTaskbarOnlyCompact")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HotkeysIsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNightMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Localization")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MainWindowAdvancedCompactPosition")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MainWindowCompactAdvancedHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MainWindowHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MainWindowLeft")
                        .HasColumnType("REAL");

                    b.Property<int>("MainWindowMode")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MainWindowTop")
                        .HasColumnType("REAL");

                    b.Property<bool>("MainWindowTopmost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MainWindowTopmostOnlyCompact")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MainWindowWidth")
                        .HasColumnType("REAL");

                    b.Property<int>("SearchEngine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowFavoritesAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowOnlyCustomAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartMinimized")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.Property<int>("VolumeStep")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9ae53f5-8500-42ae-8380-f56c90ec3cc0"),
                            AlwaysShowTrayIcon = true,
                            ExportRadiostationsAll = true,
                            ExportRadiostationsCustomOnly = false,
                            ExportRadiostationsFavoritesOnly = false,
                            ExportRadiostationsFormat = 0,
                            ExportRadiostationsOnlyFavoritesOrCustom = false,
                            ExportRadiostationsSaveFavoritesTags = true,
                            ExportRadiostationsSaveSoundSettings = true,
                            HideApplicationOnCloseButtonClick = true,
                            HideApplicationOnMinimizeButtonClick = false,
                            HideInTaskbar = false,
                            HideInTaskbarOnlyCompact = false,
                            HotkeysIsEnabled = false,
                            IsNightMode = false,
                            Localization = 0,
                            MainWindowAdvancedCompactPosition = 0,
                            MainWindowCompactAdvancedHeight = 400.0,
                            MainWindowHeight = 0.0,
                            MainWindowLeft = 0.0,
                            MainWindowMode = 0,
                            MainWindowTop = 0.0,
                            MainWindowTopmost = false,
                            MainWindowTopmostOnlyCompact = false,
                            MainWindowWidth = 0.0,
                            SearchEngine = 0,
                            ShowFavoritesAtStart = false,
                            ShowOnlyCustomAtStart = false,
                            StartMinimized = false,
                            Volume = 50.0,
                            VolumeStep = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
