// <auto-generated />
using System;
using Dartware.Radiocamp.Clients.Windows.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dartware.Radiocamp.Clients.Windows.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Dartware.Radiocamp.Clients.Windows.Core.Models.Hotkey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Command")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModifierKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("Command");

                    b.ToTable("Hotkeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3474b9a-4df6-44bb-923b-5d9935905224"),
                            Command = 1,
                            IsEnabled = true,
                            Key = 62,
                            ModifierKey = 1
                        },
                        new
                        {
                            Id = new Guid("883efdbf-21cb-43e2-959a-a138a294a987"),
                            Command = 2,
                            IsEnabled = true,
                            Key = 44,
                            ModifierKey = 1
                        },
                        new
                        {
                            Id = new Guid("9d71dcb9-9ae2-4623-8920-b2707410c01a"),
                            Command = 3,
                            IsEnabled = true,
                            Key = 47,
                            ModifierKey = 1
                        },
                        new
                        {
                            Id = new Guid("1a649e7a-0a24-4a34-bc6c-37df71abc40e"),
                            Command = 4,
                            IsEnabled = true,
                            Key = 24,
                            ModifierKey = 1
                        },
                        new
                        {
                            Id = new Guid("a3334e91-f816-47ff-8ec0-b82094435268"),
                            Command = 5,
                            IsEnabled = true,
                            Key = 26,
                            ModifierKey = 1
                        },
                        new
                        {
                            Id = new Guid("a9291976-9948-4c59-933c-777d53943685"),
                            Command = 6,
                            IsEnabled = true,
                            Key = 67,
                            ModifierKey = 1
                        });
                });

            modelBuilder.Entity("Dartware.Radiocamp.Clients.Windows.Core.Models.WindowsSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HotkeysIsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MainWindowHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MainWindowLeft")
                        .HasColumnType("REAL");

                    b.Property<double>("MainWindowTop")
                        .HasColumnType("REAL");

                    b.Property<double>("MainWindowWidth")
                        .HasColumnType("REAL");

                    b.Property<int>("SearchEngine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowFavoritesAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowOnlyCustomAtStart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StartMinimized")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("889ef244-dea0-4c94-863c-9e949b9fbb9d"),
                            HotkeysIsEnabled = false,
                            MainWindowHeight = 0.0,
                            MainWindowLeft = 0.0,
                            MainWindowTop = 0.0,
                            MainWindowWidth = 0.0,
                            SearchEngine = 0,
                            ShowFavoritesAtStart = false,
                            ShowOnlyCustomAtStart = false,
                            StartMinimized = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
